apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "strapi.fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
      annotations:
        backup.velero.io/backup-volumes: strapi-data
        # pre.hook.backup.velero.io/command: '["/bin/sh", "-c", "sqlite3 /opt/app/.tmp/data.db \".backup /opt/app/.tmp/data_backup_new.db\""]'
        pre.hook.backup.velero.io/command: '["/usr/local/bin/node", "-e", "require(\"better-sqlite3\")(\"/opt/app/.tmp/data.db\").backup(\"/opt/app/.tmp/data_backup_new.db\")"]'
        post.hook.backup.velero.io/command: '["/bin/sh", "-c", "rm /opt/app/.tmp/data_backup_new.db"]'
        post.hook.restore.velero.io/command: '["/bin/sh", "-c", "mv /opt/app/.tmp/data_backup_new.db /opt/app/.tmp/data.db"]'
    spec:
      containers:
        - name: strapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ADMIN_JWT_SECRET
              value: "temporary_secret_for_recovery"
            - name: JWT_SECRET
              value: "another_temporary_secret"
            - name: APP_KEYS
              value: "key1,key2,key3,key4"
            - name: API_TOKEN_SALT
              value: "temporary_salt"
          ports:
            - containerPort: 1337
          volumeMounts:
            - name: strapi-data
              mountPath: /opt/app/.tmp
      volumes:
        - name: strapi-data
          persistentVolumeClaim:
            claimName: strapi-sqlite-pvc
