apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "strapi.fullname" . }}
  labels:
    app: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
      annotations:
        # ХУКИ ДЛЯ VELERO (SQLite Backup)
        pre.backup.velero.io/command: '["/bin/sh", "-c", "sqlite3 /opt/app/.tmp/data.db \".backup /opt/app/.tmp/data_backup.db\""]'
        pre.backup.velero.io/container: strapi
        post.backup.velero.io/command: '["/bin/sh", "-c", "rm /opt/app/.tmp/data_backup.db"]'
        post.backup.velero.io/container: strapi
    spec:
      containers:
        - name: strapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 1337
          volumeMounts:
            - name: strapi-data
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: strapi-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "strapi.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
