apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-sqlite-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: strapi-local
  resources:
    requests:
      storage: 1Gi