apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: strapi-cms
  # namespace: {{ .Release.Namespace }}       # ns вашей команды - НЕ ОЧЕНЬ понимаю, что значит неймспейс команды, но я так понимаю он совпадает с неймспейсом ресурсов
  namespace: kube-backup
  labels:
    team: web
spec:
  schedule: "*/10 * * * *" # каждый  день
  template:
    includedNamespaces:
      - {{ .Release.Namespace }}
    defaultVolumesToFsBackup: true
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: {{ .Release.Name }}
    ttl: 2h0m0s