apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: strapi-cms     
  # namespace: {{ .Release.Namespace }}       # ns вашей команды - НЕ ОЧЕНЬ понимаю, что значит неймспейс команды, но я так понимаю он совпадает с неймспейсом ресурсов
  namespace: kube-backup
  labels:
    team: web          
spec:
  schedule: "*/2 * * * *" # каждый  2 мин
  template:
    includedNamespaces:
      - {{ .Release.Namespace }}
    includedResources:
      - persistentvolumeclaims
      - persistentvolumes
    defaultVolumesToFsBackup: true
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
    ttl: 336h0m0s         