image:
  repository: strapi-sqlite # Имя образа, который соберет Jenkins
  tag: latest
  pullPolicy: Never

port: 1337

persistence:
  enabled: true
  size: 1Gi
  mountPath: /opt/app/.tmp # Папка, где Strapi хранит sqlite базу
